default_language_version:
  python: python{{ cookiecutter.minimal_python_version }}

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py{{ cookiecutter.minimal_python_version.replace('.', '') }}-plus
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff --settings-path pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: poetry run yamllint -c=pyproject.toml --strict
        exclude: ^{{ cookiecutter.project_name }}/
        types: [file, yaml]
        language: system
