name: {{ cookiecutter.project_name }}
channels:
  - conda-forge
dependencies:
  - python={{ cookiecutter.minimal_python_version }}
  - darglint
  - mypy
  - mypy-extensions
  - pre-commit
  - pydocstyle
  - pylint
  - pytest
  - pyupgrade
  - ruff
  - pytest-html
  - pytest-cov
  - yamllint
  - pip:
      - lazy-loader